version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/code
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      python /code/stats.py
  redis:
    image: "redis:alpine"
